pipeline:
  identifier: Build_cmiller241_CalculatorTest_1715366059793
  name: Build CalculatorTest
  orgIdentifier: default
  projectIdentifier: Calculator
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1715118214843
        repoName: cmiller241/CalculatorTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Build and Run Java Application
                  identifier: Run_Java_Application
                  spec:
                    shell: Sh
                    command: |-
                      javac src/main/java/harnessio/Calculator.java
                      java -cp src/main/java harnessio.Calculator
              - step:
                  type: RunTests
                  name: Run Maven Tests
                  identifier: Run_Maven_Tests
                  spec:
                    language: Java
                    buildTool: Maven
                    args: clean test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: false
                  description: Run Maven Tests
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
